### ISSUE TITLE
Pink pixel at top left corner

### ISSUE THREAD

**Issue by InZan123** [oatmealine/simply-love-oat-fork#17]
When the window width is larger than the default width there is a pink pixel on the top left corner which doesn't go away no matter what screen is loaded.

![image](https://user-images.githubusercontent.com/69921455/181642822-10eb0bed-219d-4878-9e0f-fa17c648867b.png)

I am using 16:9 aspect ratio option but it also happens on 4:3 when the window width is larger.

**Comment by InZan123** [comment]
I found that going to Screens / Overlay > Death > default.xml and removing <Layer File="Fortnite" /> fixes the pixel for me, maybe that info will help find the better solution.

**Comment by oatmealine** [comment]
can repro the issue; can't repro your solution, however

**Comment by InZan123** [comment]
I was meant to say that removing the layer with Fortnite fixed the pixel. I'm sorry I missed that before I was prob very tired.

**Comment by NyaightHazard** [comment]
I found how to fix.
Replace _fortnite:Setup()_ in Lua/death/Fortnite.lua with this:
```
function fortnite:Setup()
    self(1):cmd("stretchto,0,0,SCREEN_WIDTH,SCREEN_HEIGHT;diffuse,1,0,0,0")
    self(2):cmd("xy,SCREEN_CENTER_X,SCREEN_CENTER_Y;diffusealpha,0;")
end
```

**Comment by oatmealine** [comment]
ty!
